"""phase5 agentic growth intelligence tables

Revision ID: c714f19a0609
Revises: 61b79451226c
Create Date: 2026-08-25 16:53:23.058743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c714f19a0609'
down_revision: Union[str, Sequence[str], None] = '61b79451226c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('importance', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('outcome_variance_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('memory_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_id'), 'agent_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memories_memory_type'), 'agent_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_agent_memories_merchant_id'), 'agent_memories', ['merchant_id'], unique=False)
    op.create_index('ix_agent_memories_merchant_type', 'agent_memories', ['merchant_id', 'memory_type'], unique=False)
    op.create_table('agent_runs',
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('orchestrator_run_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities_created', sa.Integer(), nullable=False),
    sa.Column('actions_proposed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=False),
    sa.Column('db_latency_ms', sa.Integer(), nullable=False),
    sa.Column('tool_latency_ms', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=40), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_merchant_id'), 'agent_runs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_orchestrator_run_id'), 'agent_runs', ['orchestrator_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('growth_signals',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('signal_key', sa.String(length=200), nullable=False),
    sa.Column('signal_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('comparison_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('change_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_signals_id'), 'growth_signals', ['id'], unique=False)
    op.create_index(op.f('ix_growth_signals_merchant_id'), 'growth_signals', ['merchant_id'], unique=False)
    op.create_index('ix_growth_signals_merchant_key', 'growth_signals', ['merchant_id', 'signal_key'], unique=True)
    op.create_index(op.f('ix_growth_signals_signal_type'), 'growth_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_growth_signals_status'), 'growth_signals', ['status'], unique=False)
    op.create_table('customer_insights',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('insight_key', sa.String(length=120), nullable=False),
    sa.Column('primary_segment', sa.String(length=40), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('lifetime_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=True),
    sa.Column('avg_interval_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payment_success_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('failed_payment_count', sa.Integer(), nullable=False),
    sa.Column('churn_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('churn_risk_level', sa.String(length=20), nullable=False),
    sa.Column('churn_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('churn_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategy_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_insights_customer_id'), 'customer_insights', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_insights_id'), 'customer_insights', ['id'], unique=False)
    op.create_index('ix_customer_insights_merchant_customer', 'customer_insights', ['merchant_id', 'customer_id'], unique=True)
    op.create_index(op.f('ix_customer_insights_merchant_id'), 'customer_insights', ['merchant_id'], unique=False)
    op.create_table('experiments',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('experiment_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='proposed', nullable=False),
    sa.Column('control_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('treatment_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_population_size', sa.Integer(), nullable=False),
    sa.Column('estimated_metric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['growth_opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_index(op.f('ix_experiments_merchant_id'), 'experiments', ['merchant_id'], unique=False)
    op.create_index('ix_experiments_merchant_key', 'experiments', ['merchant_id', 'experiment_key'], unique=True)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('simulations',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_agent', sa.String(length=80), nullable=True),
    sa.Column('scenario_type', sa.String(length=60), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('estimated_profit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('expected_conversion', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('expected_roi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_low', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('confidence_high', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['growth_opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_index(op.f('ix_simulations_merchant_id'), 'simulations', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_simulations_opportunity_id'), 'simulations', ['opportunity_id'], unique=False)
    op.create_table('experiment_results',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('control_conversions', sa.Integer(), nullable=False),
    sa.Column('control_size', sa.Integer(), nullable=False),
    sa.Column('treatment_conversions', sa.Integer(), nullable=False),
    sa.Column('treatment_size', sa.Integer(), nullable=False),
    sa.Column('actual_metric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uplift_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('statistical_status', sa.String(length=40), server_default='measurement_pending', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_results_id'), 'experiment_results', ['id'], unique=False)
    op.create_index(op.f('ix_experiment_results_merchant_id'), 'experiment_results', ['merchant_id'], unique=False)
    # NOTE: autogenerate drift noise intentionally removed — Phase 5 only ADDS
    # tables. The knowledge_chunks IVFFlat index and audit_events defaults
    # are untouched.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_experiment_results_merchant_id'), table_name='experiment_results')
    op.drop_index(op.f('ix_experiment_results_id'), table_name='experiment_results')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index(op.f('ix_simulations_opportunity_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_merchant_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index('ix_experiments_merchant_key', table_name='experiments')
    op.drop_index(op.f('ix_experiments_merchant_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_customer_insights_merchant_id'), table_name='customer_insights')
    op.drop_index('ix_customer_insights_merchant_customer', table_name='customer_insights')
    op.drop_index(op.f('ix_customer_insights_id'), table_name='customer_insights')
    op.drop_index(op.f('ix_customer_insights_customer_id'), table_name='customer_insights')
    op.drop_table('customer_insights')
    op.drop_index(op.f('ix_growth_signals_status'), table_name='growth_signals')
    op.drop_index(op.f('ix_growth_signals_signal_type'), table_name='growth_signals')
    op.drop_index('ix_growth_signals_merchant_key', table_name='growth_signals')
    op.drop_index(op.f('ix_growth_signals_merchant_id'), table_name='growth_signals')
    op.drop_index(op.f('ix_growth_signals_id'), table_name='growth_signals')
    op.drop_table('growth_signals')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_orchestrator_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_merchant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_agent_memories_merchant_type', table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_merchant_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_memory_type'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
